from __future__ import annotations

import pytest

from glyph.core.models import CompressionProfile, GlyphManifest
from glyph.formats.parser import parse_glp
from glyph.formats.renderer import render_glp


def representative_manifest() -> GlyphManifest:
    return GlyphManifest(
        agent="backend",
        goal=["maintain_improve", "fastapi_backend"],
        stack=["python", "fastapi", "postgres", "pytest"],
        scope=["src/", "tests/"],
        flow=["read", "plan", "minimal_change", "test", "report"],
        commands={"install": "pip install -e .", "test": "pytest"},
        must=["read_before_edit", "run_tests_before_done", "report_changes"],
        deny=["secrets_commit", "prod_config_write"],
        ask=["destructive_ops", "schema_changes"],
    )


@pytest.mark.parametrize("profile", list(CompressionProfile))
def test_parse_render_all_v01_profiles(profile: CompressionProfile):
    rendered = render_glp(representative_manifest(), profile)
    parsed = parse_glp(rendered)
    assert parsed.agent == "backend" or profile == CompressionProfile.ultra
    assert parsed.stack == ["fastapi", "postgres", "pytest", "python"]
    assert parsed.scope == ["src/", "tests/"] or profile == CompressionProfile.ultra
    assert parsed.commands["test"] == "pytest"
    assert "run_tests_before_done" in parsed.must
    assert "secrets_commit" in parsed.deny
    assert "destructive_ops" in parsed.ask


def test_glp_comments_and_whitespace_are_ignored():
    parsed = parse_glp(
        """
# generated by glyph
glyph/0.1

agent coding

stack[ python, pytest ]

# safety
deny[
  secrets_commit
]
ask[ destructive_ops ]
"""
    )
    assert parsed.agent == "coding"
    assert parsed.stack == ["pytest", "python"]
    assert parsed.deny == ["secrets_commit"]
    assert parsed.ask == ["destructive_ops"]


def test_parse_render_parse_round_trip_semantic_equivalence():
    first = parse_glp(render_glp(representative_manifest(), CompressionProfile.readable))
    second = parse_glp(render_glp(first, CompressionProfile.compact))
    assert first.model_dump(exclude={"provenance"}) == second.model_dump(exclude={"provenance"})


def test_parser_supports_existing_generated_compact_glp():
    text = "glyph/0.1\nstack[python,pytest]\nflow[read,test]\ncmd.test \"pytest\"\nmust[run_tests_before_done]\ndeny[secrets_commit]\nask[destructive_ops]\n"
    manifest = parse_glp(text)
    assert manifest.stack == ["pytest", "python"]
    assert manifest.flow == ["read", "test"]
    assert manifest.commands == {"test": "pytest"}
