from __future__ import annotations

from ..core.models import SemanticRule


def R(**kwargs: object) -> SemanticRule:
    return SemanticRule(**kwargs)  # type: ignore[arg-type]


RULES: list[SemanticRule] = [
    R(id="read_before_edit", category="must", patterns=["read relevant files before", "read the relevant files before", "read files before", "inspect existing", "understand the code before", "look through the existing"], positive_terms=["read", "inspect", "review", "understand"], required_context_terms=["before", "editing", "changes"], section_hints=["workflow", "process", "agent instructions"], modal_hints=["before", "always"], rendered="Read the relevant files before editing."),
    R(id="plan_before_edit", category="must", patterns=["create a short plan", "make a plan before", "plan before editing", "short plan"], positive_terms=["plan", "approach"], required_context_terms=["before", "editing", "non-trivial"], section_hints=["workflow", "process"], modal_hints=["before", "create"], rendered="Create a short plan before non-trivial edits."),
    R(id="minimal_change", category="must", patterns=["smallest safe change", "minimal change", "small focused change", "make the smallest"], positive_terms=["smallest", "minimal", "focused"], section_hints=["workflow", "constraints"], modal_hints=["make", "keep"], rendered="Make the smallest safe change that solves the task."),
    R(id="run_tests_before_done", category="must", patterns=["always run tests", "run tests before", "run the relevant tests", "test suite before", "tests pass before", "tests must pass", "all tests must pass", "suite is green", "before opening a pr", "before merging", "before completion", "before considering the task complete", "before saying the task is complete", "before marking work done"], positive_terms=["test", "tests", "suite", "green", "pytest", "unit tests", "e2e"], required_context_terms=["before", "done", "completion", "complete", "pr", "merge", "pass"], section_hints=["testing", "pull requests", "completion criteria", "done criteria"], modal_hints=["always", "before", "make sure", "required", "must"], rendered="Run the test suite before considering the task complete.", severity="high"),
    R(id="simple_explicit_code", category="must", patterns=["simple explicit code", "prefer simple", "clear code", "avoid clever"], positive_terms=["simple", "explicit", "clear"], negative_terms=["clever"], section_hints=["style", "repository conventions"], modal_hints=["prefer", "avoid"], rendered="Prefer simple, explicit code over clever abstractions."),
    R(id="small_reviewable_changes", category="must", patterns=["small reviewable", "small and reviewable", "reviewable changes", "focused changes", "focused pr", "keep the pr focused", "keep visual changes scoped", "avoid touching unrelated"], positive_terms=["small", "reviewable", "focused", "unrelated", "scoped"], section_hints=["workflow", "pull requests", "contributing"], modal_hints=["keep", "avoid"], rendered="Keep changes small and reviewable."),
    R(id="explain_unrun_tests", category="must", patterns=["explain unrun tests", "if tests are not run", "if tests cannot be run", "when tests cannot be run", "cannot be run, explain", "explain any check", "check was skipped", "verification was skipped"], positive_terms=["explain", "state why", "skipped"], required_context_terms=["test", "verification", "checks", "check"], section_hints=["reporting", "completion criteria"], modal_hints=["if", "when"], rendered="Explain any tests that were not run."),
    R(id="report_changes", category="must", patterns=["report what changed", "report changes", "summarize changes", "describe changes", "what changed"], positive_terms=["report", "summarize", "describe"], required_context_terms=["changed", "changes"], section_hints=["reporting", "completion criteria"], modal_hints=["report", "summarize"], rendered="Report what changed.", always_select=True),
    R(id="report_verification", category="must", patterns=["report what was verified", "verification performed", "report verification", "what was verified", "mention verified", "report exactly what was checked", "report the exact commands", "exact commands that ran"], positive_terms=["verified", "verification", "checks", "commands"], section_hints=["reporting", "completion criteria"], modal_hints=["report", "mention"], rendered="Report what was verified.", always_select=True),
    R(id="lint_before_done", category="must", patterns=["run lint", "lint before", "ruff check", "eslint", "before done lint"], positive_terms=["lint", "ruff", "eslint"], required_context_terms=["before", "done", "completion"], section_hints=["linting", "testing", "quality"], modal_hints=["run", "before"], rendered="Run lint checks before completion."),
    R(id="typecheck_before_done", category="must", patterns=["typecheck", "type check", "mypy", "tsc", "pyright"], positive_terms=["typecheck", "type check", "mypy", "tsc", "pyright"], section_hints=["type checking", "testing", "quality"], modal_hints=["run", "before"], rendered="Run type checks before completion."),
    R(id="verify_build_before_done", category="must", patterns=["run the build", "build before", "verify the build", "production bundle", "build must pass"], positive_terms=["build", "bundle"], required_context_terms=["before", "done", "completion", "pr", "merge"], section_hints=["build", "testing", "quality", "pull requests"], modal_hints=["run", "verify", "before", "make sure"], rendered="Verify the build before completion.", severity="high"),
    R(id="update_docs_when_behavior_changes", category="must", patterns=["update docs when behavior changes", "update documentation when behavior changes", "document behavior changes", "documentation with behavior changes", "docs for behavior changes"], positive_terms=["docs", "documentation", "document"], required_context_terms=["behavior", "changes", "changed"], section_hints=["documentation", "pull requests", "contributing", "workflow"], modal_hints=["update", "document", "when"], rendered="Update documentation when behavior changes."),
    R(id="prefer_existing_patterns", category="must", patterns=["prefer existing patterns", "follow existing patterns", "match existing patterns", "reuse existing patterns"], positive_terms=["existing", "patterns", "conventions"], section_hints=["style", "repository conventions", "workflow"], modal_hints=["prefer", "follow", "match", "reuse"], rendered="Prefer existing patterns and conventions."),
    R(id="use_existing_helpers", category="must", patterns=["use existing helpers", "use existing repository helpers", "use shared helpers", "shared helper", "shared database helper", "shared ui primitives", "reuse shared"], positive_terms=["shared", "helper", "helpers", "primitives", "reuse"], negative_terms=["tenant resolver"], section_hints=["repository conventions", "architecture", "database", "frontend", "workflow"], modal_hints=["use", "prefer", "reuse"], rendered="Use existing shared helpers and primitives."),
    R(id="preserve_service_boundaries", category="must", patterns=["keep service boundaries clear", "preserve service boundaries", "respect service boundaries"], positive_terms=["service boundaries", "boundaries"], section_hints=["architecture", "backend", "repository conventions"], modal_hints=["keep", "preserve", "respect"], rendered="Preserve service boundaries."),
    R(id="validate_database_migrations", category="must", patterns=["validate migrations", "validate database migrations", "test migrations", "migration rollback", "migration plan", "verify migrations"], positive_terms=["migration", "migrations", "rollback"], required_context_terms=["test", "validate", "verify", "plan"], section_hints=["database", "deployment", "safety"], modal_hints=["validate", "test", "verify", "run"], rendered="Validate database migrations before completion.", severity="high", safety_critical=True, always_select=True),
    R(id="follow_existing_style", category="must", patterns=["follow existing style", "match existing style", "existing conventions", "project conventions", "repository conventions"], positive_terms=["style", "conventions", "patterns"], section_hints=["style", "repository conventions"], modal_hints=["follow", "match"], rendered="Follow existing repository style and conventions."),
    R(id="preserve_accessibility", category="must", patterns=["preserve accessibility", "keep accessibility", "a11y", "keyboard navigation", "screen reader", "aria"], positive_terms=["accessibility", "a11y", "keyboard", "screen reader", "aria"], section_hints=["frontend", "ui", "accessibility", "testing"], modal_hints=["preserve", "keep", "verify", "do not"], rendered="Preserve accessibility behavior."),
    R(id="keep_pr_focused", category="must", patterns=["keep pr focused", "keep the pr focused", "keep prs focused", "keep pull requests focused", "focused pull request", "one concern per pr", "branch focused", "keep the scope narrow"], positive_terms=["pr", "pull request", "focused", "branch", "scope"], section_hints=["pull requests", "contributing", "workflow"], modal_hints=["keep"], rendered="Keep each pull request focused."),
    R(id="document_breaking_changes", category="must", patterns=["document breaking changes", "call out breaking changes", "breaking change", "migration notes"], positive_terms=["breaking", "migration notes"], section_hints=["pull requests", "release", "documentation"], modal_hints=["document", "call out", "explain"], rendered="Document breaking changes.", severity="high"),
    R(id="report_security_impact", category="must", patterns=["report security impact", "explain whether a path touches authentication", "explain security impact", "call out security impact", "touches authentication", "touches authorization", "audit visibility"], positive_terms=["authentication", "authorization", "audit", "security"], section_hints=["security", "pull requests", "review"], modal_hints=["explain", "call out", "report"], rendered="Report security impact for sensitive changes.", severity="high", safety_critical=True, always_select=True),
    R(id="report_audit_event_fields", category="must", patterns=["report whether new events contain", "audit fixtures", "audit event"], positive_terms=["audit", "events", "identifiers", "timestamps"], section_hints=["security", "audit", "privacy"], modal_hints=["report"], rendered="Report sensitive audit-event fields."),
    R(id="report_data_change_impact", category="must", patterns=["report the partition range", "affected partitions", "expected row-count", "rollback approach", "source dataset, target dataset"], positive_terms=["partition", "dataset", "row-count", "rollback"], section_hints=["data", "pipeline", "backfill", "review"], modal_hints=["report", "include"], rendered="Report data-change scope and rollback details.", severity="high"),
    R(id="no_large_refactors", category="deny", patterns=["no large refactors", "avoid large refactors", "do not refactor unrelated", "unrequested refactors", "broad rewrites", "avoid broad rewrites", "unrelated packages"], positive_terms=["refactor", "rewrite", "broad", "unrelated"], section_hints=["constraints", "workflow"], modal_hints=["avoid", "do not", "never"], rendered="Do not perform large unrequested refactors."),
    R(id="no_unrequested_features", category="deny", patterns=["no unrequested features", "do not add unrequested features", "do not add features", "avoid unrequested features"], positive_terms=["feature", "unrequested"], section_hints=["constraints"], modal_hints=["do not", "avoid", "never"], rendered="Do not add unrequested features."),
    R(id="avoid_generated_files", category="deny", patterns=["do not edit generated files", "do not edit generated openapi", "generated api clients", "generated clients", "avoid generated files", "generated files unless", "do not modify generated", "generated snapshots", "generated file changes", "changed by their generation command", "generated files out of manual edits"], positive_terms=["generated", "snapshots"], section_hints=["safety", "repository conventions", "workflow"], modal_hints=["avoid", "do not", "never"], rendered="Do not edit generated files unless explicitly required."),
    R(id="do_not_edit_lockfiles_unless_needed", category="deny", patterns=["do not edit lockfiles", "do not change lockfiles", "avoid lockfile changes", "lockfiles unless", "lockfiles without", "package-lock", "pnpm-lock", "poetry.lock"], positive_terms=["lockfile", "lockfiles", "package-lock", "pnpm-lock", "poetry.lock"], section_hints=["dependencies", "safety", "workflow"], modal_hints=["avoid", "do not", "unless"], rendered="Do not edit lockfiles unless dependency changes require it."),
    R(id="preserve_public_api", category="deny", patterns=["preserve public api", "preserve public apis", "do not break public api", "avoid breaking api", "public api changes", "public apis", "backward compatibility"], positive_terms=["public api", "public apis", "api", "backward compatibility", "breaking"], section_hints=["api", "compatibility", "pull requests"], modal_hints=["preserve", "do not", "avoid"], rendered="Do not break public APIs without an explicit migration plan.", severity="high"),
    R(id="avoid_unrelated_packages", category="deny", patterns=["avoid unrelated packages", "do not touch unrelated packages", "unrelated packages", "outside the package", "unrelated workspace"], positive_terms=["package", "packages", "workspace", "unrelated"], section_hints=["monorepo", "repository conventions", "workflow"], modal_hints=["avoid", "do not"], rendered="Do not modify unrelated packages."),
    R(id="avoid_raw_database_connections", category="deny", patterns=["raw database connections", "raw connections", "ad hoc database connections", "manual database connection"], positive_terms=["raw", "ad hoc", "manual", "database connection", "connections"], negative_terms=["tenant resolver"], section_hints=["database", "architecture", "safety"], modal_hints=["avoid", "do not", "rather than", "instead"], rendered="Do not open raw database connections when shared helpers exist.", severity="high", safety_critical=True),
    R(id="avoid_dependency_changes_without_reason", category="deny", patterns=["avoid dependency changes", "do not change dependencies", "dependency changes without", "dependency versions", "new dependency", "dependencies without reason"], positive_terms=["dependency", "dependencies", "package"], section_hints=["dependencies", "workflow", "pull requests"], modal_hints=["avoid", "do not", "without"], rendered="Do not change dependencies without a clear reason."),
    R(id="avoid_large_dependency_additions", category="deny", patterns=["large dependency", "large dependencies", "heavy dependency", "avoid large dependencies", "large dependency additions", "do not add large dependencies"], positive_terms=["large dependency", "large dependencies", "heavy dependency", "dependency additions"], section_hints=["dependencies", "architecture"], modal_hints=["avoid", "do not"], rendered="Avoid large dependency additions without justification."),
    R(id="do_not_modify_ci_without_reason", category="deny", patterns=["do not modify ci", "avoid ci changes", "ci changes without", "github actions without", "workflow files without"], positive_terms=["ci", "github actions", "workflow files"], section_hints=["ci", "workflow", "safety"], modal_hints=["avoid", "do not", "without"], rendered="Do not modify CI configuration without a clear reason.", severity="high"),
    R(id="do_not_commit_debug_logs", category="deny", patterns=["do not commit debug logs", "debug logs", "console.log", "print debugging", "temporary logging", "debug screenshots", "generated trace files", "temporary console logs", "temporary csv files", "debug row dumps", "notebook outputs"], positive_terms=["debug", "logs", "console.log", "temporary logging", "screenshots", "trace", "csv", "dumps"], section_hints=["safety", "workflow", "pull requests"], modal_hints=["do not", "avoid", "remove"], rendered="Do not commit temporary debug logs."),
    R(id="avoid_touching_secrets_or_env_files", category="deny", patterns=["do not edit env files", "do not touch `.env` files", "do not touch .env files", "avoid env files", ".env files", "secret files", "secrets files", "touch secrets"], positive_terms=[".env", "env files", "secret files", "secrets files", "secrets"], section_hints=["security", "safety"], modal_hints=["avoid", "do not", "never"], rendered="Do not touch secrets or environment files unless explicitly requested.", severity="high", safety_critical=True, always_select=True),
    R(id="secrets_commit", category="deny", patterns=["never commit secrets", "do not commit secrets", "secrets tokens api keys", "include secrets in", "commit credentials", "real values", "production extracts", "real user data"], positive_terms=["secret", "secrets", "credential", "credentials", "token", "api key", "real values", "production extracts"], required_context_terms=["commit", "repository", "code", "tests", "logs", "fixtures"], section_hints=["security", "safety"], modal_hints=["never", "do not", "avoid"], rendered="Never commit secrets, tokens, API keys, or credentials.", severity="high", safety_critical=True, always_select=True),
    R(id="prod_config_write", category="deny", patterns=["production config", "prod config", "do not modify production", "production settings"], positive_terms=["production", "prod", "configuration", "settings"], section_hints=["security", "deployment", "safety"], modal_hints=["do not", "never", "ask"], rendered="Do not write production configuration without approval.", severity="high", safety_critical=True, always_select=True),
    R(id="credentials_exposure", category="deny", patterns=["do not expose credentials", "expose credentials", "leak credentials", "credentials exposure", "commit credentials", "never commit secrets, credentials"], positive_terms=["credential", "credentials", "secret"], required_context_terms=["expose", "leak", "logs", "fixtures", "examples", "commit"], section_hints=["security", "safety"], modal_hints=["do not", "never"], rendered="Do not expose credentials.", severity="high", safety_critical=True, always_select=True),
    R(id="api_key_exposure", category="deny", patterns=["api keys", "api key", "tokens", "private key"], positive_terms=["api key", "api keys", "token", "tokens", "private key"], section_hints=["security", "safety"], modal_hints=["do not", "never"], rendered="Do not expose API keys or tokens.", severity="high", safety_critical=True, always_select=True),
    R(id="unsafe_migrations", category="deny", patterns=["unsafe migration", "destructive migration", "drop table", "irreversible migration"], positive_terms=["unsafe", "destructive", "irreversible", "drop table"], required_context_terms=["migration", "migrations"], section_hints=["database", "deployment", "safety"], modal_hints=["do not", "ask", "never"], rendered="Do not run unsafe migrations without approval.", severity="high", safety_critical=True, always_select=True),
    R(id="deploy_without_approval", category="deny", patterns=["deploy without approval", "do not deploy", "never deploy", "production deploy"], positive_terms=["deploy", "deployment", "release"], required_context_terms=["approval", "production"], section_hints=["deploy", "deployment"], modal_hints=["do not", "never", "ask"], rendered="Do not deploy without approval.", severity="high", safety_critical=True, always_select=True),
    R(id="cache_clear_permission", category="ask", patterns=["never delete or clear the cache without explicit permission", "use --no-cache flag instead", "always use --no-cache"], positive_terms=["cache", "no-cache"], required_context_terms=["permission", "instead"], section_hints=["debugging", "troubleshooting", "evaluations", "cache"], modal_hints=["never", "permission", "instead"], rendered="Never delete or clear the cache without explicit permission; use `--no-cache` instead.", severity="high", safety_critical=True, always_select=True),
    R(id="destructive_ops", category="ask", patterns=["ask for confirmation before destructive", "confirm before destructive", "approval before destructive", "destructive operations", "delete data", "deleting files", "rm -rf", "destructive backfills", "rewriting historical partitions"], positive_terms=["destructive", "delete", "deleting", "drop", "rm -rf", "backfill"], section_hints=["ask first", "security", "safety", "deployment"], modal_hints=["ask", "confirm", "approval", "before"], rendered="Ask for confirmation before destructive operations.", severity="high", safety_critical=True, always_select=True),
    R(id="schema_changes", category="ask", patterns=["schema changes", "database schema", "migration approval", "ask before migration"], positive_terms=["schema", "database", "migration"], section_hints=["database", "deployment"], modal_hints=["ask", "approval", "before"], rendered="Ask before schema changes.", severity="high", safety_critical=True, always_select=True),
    R(id="security_sensitive_changes", category="ask", patterns=["security sensitive", "security-sensitive", "auth changes", "permission changes", "authorization changes"], positive_terms=["security", "auth", "authorization", "permission"], section_hints=["security", "safety"], modal_hints=["ask", "approval", "before"], rendered="Ask before security-sensitive changes.", severity="high", safety_critical=True, always_select=True),
    R(id="respect_package_boundaries", category="ask", patterns=["package boundaries", "respect package boundaries", "cross-package changes", "workspace boundaries", "ownership boundaries"], positive_terms=["package boundaries", "ownership boundaries", "workspace"], section_hints=["monorepo", "repository conventions", "pull requests"], modal_hints=["ask", "respect", "before"], rendered="Ask before crossing package or ownership boundaries."),
    R(id="data_retention_changes", category="ask", patterns=["retention windows", "partition pruning", "personally identifiable information handling", "warehouse permissions", "retention behavior"], positive_terms=["retention", "partition pruning", "permissions"], section_hints=["data", "pipeline", "security", "privacy"], modal_hints=["ask", "before"], rendered="Ask before changing retention, partition pruning, or warehouse permissions.", severity="high", safety_critical=True),
]

RULE_BY_ID = {rule.id: rule for rule in RULES}


def ordered_rule_ids() -> list[str]:
    return [rule.id for rule in RULES]


def match_rules(text: str) -> list[SemanticRule]:
    lowered = " ".join(text.lower().split())
    hits: list[SemanticRule] = []
    for rule in RULES:
        if any(pattern in lowered for pattern in rule.patterns):
            hits.append(rule)
    if "never" in lowered or "do not" in lowered:
        if "secret" in lowered:
            hits.append(RULE_BY_ID["secrets_commit"])
        if "credential" in lowered:
            hits.append(RULE_BY_ID["credentials_exposure"])
        if "api key" in lowered or "token" in lowered:
            hits.append(RULE_BY_ID["api_key_exposure"])
    return list({rule.id: rule for rule in hits}.values())
